/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import static java.lang.System.exit;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JLabel;

import model.Usuario;
import view.TelaAlunos;
import view.TelaCadastroAvaliacao;
import view.TelaCadastroCurso;
import view.TelaCadastroProfessor;
import view.TelaCadastroTurma;
import view.TelaLogin;

/**
 *
 * @author abcvt
 */
public class TelaPrincipalProfessor extends javax.swing.JFrame {
	private Usuario usuario;	
    
    public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipalProfessor() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setBounds(100, 100, 1024, 600);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuHome = new javax.swing.JMenu();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadastroAvaliacao = new javax.swing.JMenuItem();
        jMenuItemCadastroNotas = new javax.swing.JMenuItem();
        jMenuConsulta = new javax.swing.JMenu();
        jMenuItemConsultaAluno = new javax.swing.JMenuItem();
        jMenuItemConsultaCurso = new javax.swing.JMenuItem();
        jMenuItemConsultaTurma = new javax.swing.JMenuItem();
        jMenuItemConsultaDisciplina = new javax.swing.JMenuItem();
        jMenuItemConsultaAvaliacao = new javax.swing.JMenuItem();
        jMenuItemConsultaNotas = new javax.swing.JMenuItem();
        jMenuItemConsultaGrade = new javax.swing.JMenuItem();
        jMenuItemConsultaMetasPrazos = new javax.swing.JMenuItem();
        jMenuItemConsultaSala = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Professor SCOA");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/_007f97-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jMenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home-icon.png"))); // NOI18N
        jMenuHome.setText("Home");
        jMenuHome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHomeMouseClicked(evt);
            }
        });
        jMenuHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHomeActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuHome);

        jMenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Database-icon.png"))); // NOI18N
        jMenuCadastro.setText("Cadastro");
        jMenuCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItemCadastroAvaliacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Documents-icon.png"))); // NOI18N
        jMenuItemCadastroAvaliacao.setText("Avaliação");
        jMenuItemCadastroAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroAvaliacaoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroAvaliacao);

        jMenuItemCadastroNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Test-paper-icon.png"))); // NOI18N
        jMenuItemCadastroNotas.setText("Notas");
        jMenuItemCadastroNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroNotasActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroNotas);

        jMenuBar1.add(jMenuCadastro);

        jMenuConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Zoom-icon.png"))); // NOI18N
        jMenuConsulta.setText("Consulta");
        jMenuConsulta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItemConsultaAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Person-Male-Light-icon.png"))); // NOI18N
        jMenuItemConsultaAluno.setText("Aluno");
        jMenuItemConsultaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaAlunoActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuItemConsultaAluno);

        jMenuItemConsultaCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Books-icon.png"))); // NOI18N
        jMenuItemConsultaCurso.setText("Curso");
        jMenuConsulta.add(jMenuItemConsultaCurso);

        jMenuItemConsultaTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Science-Classroom-icon.png"))); // NOI18N
        jMenuItemConsultaTurma.setText("Turma");
        jMenuItemConsultaTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaTurmaActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuItemConsultaTurma);

        jMenuItemConsultaDisciplina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Book-icon.png"))); // NOI18N
        jMenuItemConsultaDisciplina.setText("Disciplina");
        jMenuItemConsultaDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaDisciplinaActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuItemConsultaDisciplina);

        jMenuItemConsultaAvaliacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Documents-icon.png"))); // NOI18N
        jMenuItemConsultaAvaliacao.setText("Avaliação");
        jMenuItemConsultaAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaAvaliacaoActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuItemConsultaAvaliacao);

        jMenuItemConsultaNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Test-paper-icon.png"))); // NOI18N
        jMenuItemConsultaNotas.setText("Notas");
        jMenuConsulta.add(jMenuItemConsultaNotas);

        jMenuItemConsultaGrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Calendar-icon.png"))); // NOI18N
        jMenuItemConsultaGrade.setText("Grade");
        jMenuItemConsultaGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaGradeActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuItemConsultaGrade);

        jMenuItemConsultaMetasPrazos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Clock-icon (1).png"))); // NOI18N
        jMenuItemConsultaMetasPrazos.setText("Metas e Prazos");
        jMenuConsulta.add(jMenuItemConsultaMetasPrazos);

        jMenuItemConsultaSala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/62991-door-icon.png"))); // NOI18N
        jMenuItemConsultaSala.setText("Sala");
        jMenuItemConsultaSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaSalaActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuItemConsultaSala);

        jMenuBar1.add(jMenuConsulta);

        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Badge-multiply-icon.png"))); // NOI18N
        jMenuSair.setText("Sair");
        jMenuSair.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        exit(0);
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jMenuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHomeMouseClicked
        this.setVisible(false);
        TelaLogin telaLogin = new TelaLogin();
        telaLogin.setVisible(true);
        
    }//GEN-LAST:event_jMenuHomeMouseClicked

    private void jMenuItemCadastroAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroAvaliacaoActionPerformed
        this.setVisible(false);
        try {
            TelaCadastroAvaliacao telaAvaliacao = new TelaCadastroAvaliacao();
            telaAvaliacao.setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(TelaPrincipalProfessor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemCadastroAvaliacaoActionPerformed

    private void jMenuItemConsultaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaAlunoActionPerformed
        this.setVisible(false);
        TelaAlunos telaAluno = new TelaAlunos();
        telaAluno.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaAlunoActionPerformed

    private void jMenuItemConsultaTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaTurmaActionPerformed
        this.setVisible(false);
        TelaTurmas telaTurma = new TelaTurmas();
        telaTurma.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaTurmaActionPerformed

    private void jMenuItemConsultaDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaDisciplinaActionPerformed
        this.setVisible(false);
        TelaDisciplinas telaDisciplina = new TelaDisciplinas();
        telaDisciplina.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaDisciplinaActionPerformed

    private void jMenuItemConsultaAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaAvaliacaoActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemConsultaAvaliacaoActionPerformed

    private void jMenuItemConsultaGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaGradeActionPerformed
        this.setVisible(false);
        TelaGrades telaGrade = new TelaGrades();
        telaGrade.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaGradeActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHomeActionPerformed
        this.setVisible(false);
        TelaLogin telaLogin = new TelaLogin();
        telaLogin.setVisible(true);
    }//GEN-LAST:event_jMenuHomeActionPerformed

    private void jMenuItemConsultaSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaSalaActionPerformed
        this.setVisible(false);
        TelaSalas telaSala = new TelaSalas();
        telaSala.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaSalaActionPerformed

    private void jMenuItemCadastroNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroNotasActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemCadastroNotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuConsulta;
    private javax.swing.JMenu jMenuHome;
    private javax.swing.JMenuItem jMenuItemCadastroAvaliacao;
    private javax.swing.JMenuItem jMenuItemCadastroNotas;
    private javax.swing.JMenuItem jMenuItemConsultaAluno;
    private javax.swing.JMenuItem jMenuItemConsultaAvaliacao;
    private javax.swing.JMenuItem jMenuItemConsultaCurso;
    private javax.swing.JMenuItem jMenuItemConsultaDisciplina;
    private javax.swing.JMenuItem jMenuItemConsultaGrade;
    private javax.swing.JMenuItem jMenuItemConsultaMetasPrazos;
    private javax.swing.JMenuItem jMenuItemConsultaNotas;
    private javax.swing.JMenuItem jMenuItemConsultaSala;
    private javax.swing.JMenuItem jMenuItemConsultaTurma;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
